apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drivertest2
  namespace: default
spec:
  encryptedData:
    variables.0: AQA8gqfGF+PUTA//fp2rPGZc+/2M5YjTAen5yOGw8KWihgc5Fxr5knFE5u/eRDLjpIxsCgWETeCg8wH8+Tp3Pgdt3TVwEBWl1YIu0eHygl2N1fT4gU2WySjT6HJVArE+j3n8pSaH9Ob6B8g57OOgfxlkSgEzMH/tjLfu/9KSyvgZJB1w/f99Md5/SQQRi1wv57QvCgTWY946BtLGD7TIdQx1AXPTej8bKdd6CkrKoGzGMwFPBKB5vXYRJfAOeD8oZSdzWJoNrgObNAAqGbc1YrCu9D0mO21/2t0WIxYW7QlDKMyYxv3GByyv4Bt3IWW1yeuq0EQJx67FRy+uV8PSvNn3uqPndT7qBKQicQkZsBbdKg==
  template:
    metadata:
      creationTimestamp: null
      name: drivertest2
      namespace: default

