apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: optouttestenv
  namespace: default
spec:
  encryptedData:
    variables.1: AQAO8paxnUZ/q3lJ1KfoYjo9zIu8x7mMrvRq18YaENH4PL4TH2v+PW/138xjJ8kzBjay5UsEndzy6W+RBF15YgE3UgJvVmrxT4P6K/mhxFlekpTZtfIc6rfcfE88uFhebTAtX4r6VbmlH/2xcsoyYwOJTPrmn7qyvj+CJ/jsWukPe709Ng1CEj9TREUsuGjKMQ4io+hbH9Pg6r5jnUvNqRXwI9IqvthyJgBUw3yFE4lf4eMlh7MaOUsIGRcgl17rBYYiD82wKnnm2ifDSbB4KDVj46Lco/70PPrNXPIpsw3ypBG1WJUQjr5otWXA+bHpR49lTe0fZy7BaGJ7gcHvb5BJvdtdoGPjs7iOImgdLuDmJAb406+xKA0YFwz9YA==
  template:
    metadata:
      creationTimestamp: null
      name: optouttestenv
      namespace: default

