apiVersion: integrations.k8smgmt.io/v3
kind: SecretStore
metadata:
  name: test1
  project: defaultproject
spec:
  config:
    vault:
      clusters:
      - authPath: kubernetes/vijayseks15042024
        clusterName: vijayseks15042024
      host: http://vault.vault.svc:8200
  provider: Vault
