apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: alertmanager
  project: defaultproject
spec:
  base:
    name: default
    version: 1.27.0
  defaultAddons:
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
