apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bpfromgolden
  project: defaultproject
spec:
  base:
    name: goldenbp
    version: v3
  defaultAddons:
    enableIngress: false
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v5
