apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bpfromgolden
  project: defaultproject
spec:
  base:
    name: goldenbp
    version: v2
  defaultAddons:
    enableIngress: false
    enableMonitoring: true
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: testpolicy
      version: v1
    profile:
      name: default
      version: latest
  type: custom
  version: v2
