apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bpfromgolden
  project: defaultproject
spec:
  base:
    name: goldenbp
    version: v3
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  opaPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v4
