apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: cert-monitor
  project: defaultproject
spec:
  base:
    name: default
    version: 1.25.0
  customAddons:
  - name: cert-monitor
    version: v1
  - name: certmanager
    version: v1
  defaultAddons:
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v2
