apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custombp8127
  project: defaultproject
spec:
  base:
    name: minimal
    version: 1.28.0
  defaultAddons:
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v0
