apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: minimaltest
  project: defaultproject
spec:
  base:
    name: default
    version: 1.28.0
  customAddons:
  - name: corednscm
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
