apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: nssync
  project: defaultproject
spec:
  base:
    name: minimal
    version: 1.24.0
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
  type: custom
  version: v1
