apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: openebs11
  project: defaultproject
spec:
  base:
    name: minimal
    version: 1.28.0
  driftWebhook:
    enabled: true
  type: custom
  version: v1
