apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: openebs
  project: defaultproject
spec:
  base:
    name: minimal
    version: 1.25.0
  customAddons:
  - name: openebs-custom
    version: v1
  driftWebhook:
    enabled: true
  type: custom
  version: v1
