apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: secretstore
  project: defaultproject
spec:
  base:
    name: minimal
    version: 1.24.0
  defaultAddons:
    csiSecretStoreConfig:
      enableSecretRotation: true
      providers: {}
      syncSecrets: true
    enableCsiSecretStore: true
  driftWebhook:
    enabled: true
  type: custom
  version: v3
