apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testgolden
  project: defaultproject
spec:
  base:
    name: default
    version: 1.28.0
  customAddons:
  - name: vault
    version: v1
  - dependsOn:
    - vault
    name: openebs-custom
    version: v1
  - dependsOn:
    - vault
    - openebs-custom
    name: nginx
    version: v1
  - dependsOn:
    - vault
    - openebs-custom
    - nginx
    name: metallbyaml-addon
    version: v1
  - dependsOn:
    - vault
    - openebs-custom
    - nginx
    - metallbyaml-addon
    name: hello-world
    version: "1"
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: golden
  version: v1
