apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: optouttestenv3
  namespace: default
spec:
  encryptedData:
    variables.1: AQDW0HEU7hOCTmp5QBQyyTd+S5mGJzhbWY3bnmWtWXMtBizHAEC+65ud+OV6Ny46FC6tXpXvY1TUDxqgI69JulC79F6ULm9QbLqF6KlDipAyFStLlsNvSO94d/bv+qCv3VoJRJUw7j4YKvJE4jhrmCfJbtrP+mBySSGP59i9qDpxBmYyYDKc2UaQ6xJ8l9+5RdHpMNKb9GcNsGiBB1kcxKBCY0wWa4T/Tl5lrf7eSkwifQNQMgQNlw7QchfZ59/el7uC5eeY53qVRMoKk5O5+908jBq4A4QiEjiu3d5DvHGQhelzqW8iov0VSP3FrwL+eB7oUdu9GTvdcLoYAqxUcSt/xOdAxRMizZBp5HfZdfzZByRMbcbCUfCFdbRBAQ==
  template:
    metadata:
      creationTimestamp: null
      name: optouttestenv3
      namespace: default

