apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: mysql
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: destinationcluster
    - key: rafay.dev/clusterName
      value: sourceclustervijays
  resourceQuotas: {}
