apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: netpol
  project: defaultproject
spec:
  base:
    name: default
    version: 2.6.0
  defaultAddons:
    csiSecretStoreConfig:
      enableSecretRotation: true
      providers:
        aws: true
      syncSecrets: true
    enableCsiSecretStore: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v13
