apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: opaonly
  project: defaultproject
spec:
  base:
    name: default
    version: 2.7.0
  defaultAddons:
    enableRookCeph: true
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: testpolicy1
      version: v1
    profile:
      name: default
      version: latest
  type: custom
  version: v2
