apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: prod-gold
  project: defaultproject
spec:
  base:
    name: default
    version: 2.6.0
  customAddons:
  - name: testaddon
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  sharing:
    enabled: true
    projects:
    - name: production
  type: golden
  version: v1
