apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: test
  project: defaultproject
spec:
  agents:
  - {}
  credentials:
    password: sealed://credentials.password
    username: samanthapuri
  endpoint: https://github.com/Samanthapuri/rafaysyssync.git
  secret:
    name: file://artifacts/test/sealed-secret.yaml
  type: Git
