apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  registrySources: 
    allowedRegistries: 
    - quay.io
    - registry.redhat.io
    - legoeu.jfrog.io
    - demoapp2.com
    - example.com
    - vijaystest.com
