apiVersion: apps/v1
kind: Deployment
metadata:
  name: carshtest
  labels:
    app: carshtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carshtest
  template:
    metadata:
      labels:
        app: carshtest
    spec:
      containers:
      - name: carshtest
        image: samanthapuri/rafay-debug:v1
        command: ["/bin/sh","-c"]
        args: ["exit 1"]
