apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nutanix-cluster
  namespace: default
spec:
  encryptedData:
    variables.6: AQCyepHjO2G0HQBElIkZzCokVg+LfibvZw7aWdJmQtgX815rKLmEu2pGDSuiLyXIAWBX+y723IeOzu9Ok91qeue8IO06d+p5wUZG7sAlJQKtfM1uUuIu6Kltv43sd/EgX1ewYyjJdPe50X8onvip8/5uBMLy8HUlOreOo/wI6BPyx/z5LoJS1b85J/+NoDqv13jEN8CZtDbVCciWpLt3++Fhy1frimB6YQt3sf1oCHVtdqNfovFc3v30wtmEiFqKKHpOr5yU6+bdV+t3LMwWwiDnv0+MMqHEltz4XBA0dlblq2BthUOITsnlHaCKJ7RQuWqzL1yQe1LRg+xfK1jIgYTTsGbgtPf+ANcbrQOWAtCB+w==
    variables.7: AQBQyKBJFbNLPQJafE2RoUdJXRnrYXPcsw7W4jYViOH6h33Fuwx3yJqzm04/Z+NraBup2dAdTyFs9FP9fRlxjnZcL8fNfn6KZPWarJxwPTPYbvsv+VQkhnwLx1zEfvSBZ0B5v0sSRMojWU+ajjm7W53VFSgEZW+WsaRHjNL6xIaaF79kzzezrOnffYUTnmczO/WCngDVcctak6ZLWlV/uk9qPNnTx3iDNghlGXyaMkk/+TIG6bRkE5Q8UmnivDPquFram6OJwLQqTEhU3lMcGB7GKmJ8JFaoDTjaBBWcQxJJjDu5UoFxVca8VuGR2Wj4+x8tKKxOHdR22dpm/klzy5wDLkLv8ceMyxmRxOaaJOPCbg==
    variables.12: AQBbHWXJgkxmHpbhhGoSLKhH19GoaFpPrEdRXfcLa4OJdu44OstUhelocmJ8tluLEXtp4NVPqTUVMHQpuGjmhGzF8B3Wzb1F4nruALRv6KwH2EfQSyxKzkSy+4nJTJS1OpUbiYJsOGKfXdvTpOf+81+8M/eKU+iYZSKAzB2u58ZjH1NyPkePK1Jqrw4w7xVqa3A0/q7iIoFtgxhPbhIuTjlaXNf7rnprh0fZJmUwFeBVxYcXOgfcab2GFFeudIuqFbCEUy1TUYz/r/U4nREvHmeA9TkL8tTu0ismB+dMAhe6H7/NT6o8vyor/evUF/m/MG2vF/K6Mj15vIHaTC07UWzmT74uHmlI++wmYiUhlJ2q7A==
  template:
    metadata:
      creationTimestamp: null
      name: nutanix-cluster
      namespace: default

