apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: certmanager-new
  project: defaultproject
spec:
  artifact:
    artifact:
      chartName: cert-manager
      chartVersion: v1.10.1
      repository: cert-manager
    type: Helm
  namespace: cert-manager-app
  sharing: {}
  version: v2
