apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: karpenter
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-rafay
      chartName: karpenter
      chartVersion: v0.32.1
    type: Helm
  namespace: karpenter
  sharing: {}
