apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: opa-override-customer
  project: defaultproject
spec:
  resource:
    selector:
      name: opa-gatekeeper-3.11.0
    type: Workload
  type: Helm
  valuesPath:
    name: file://opa-override-customer/opa-override-customer.yaml
