apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    testkey: testval
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: centos
        env:
        - name: TESTVAR
          value: $(cat /tmp/testfile)
        command:
        - /bin/bash
        - -c
        - |
          HSTNM=$(cat /etc/hostname)
          echo $HSTNM
          echo "hi"
          sleep 6000
        
        
