apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: aks-cilium
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.2.0
  customAddons:
  - name: cilium-config
    version: v1
  - dependsOn:
    - cilium-config
    name: cilium-app
    version: v2
  driftWebhook:
    enabled: true
  type: custom
  version: v2
