apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom
  project: defaultproject
spec:
  base:
    name: default-upstream
    version: 2.4.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    enableRookCeph: true
  driftWebhook:
    enabled: true
  sharing:
    enabled: true
    projects:
    - name: '*'
  type: custom
  version: v1
