apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-bp
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.4.0
  defaultAddons:
    enableRookCeph: true
  driftWebhook:
    enabled: true
  type: custom
  version: v3
