apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custombpwithcost
  project: defaultproject
spec:
  base:
    name: default
    version: 2.2.0
  costProfile:
    name: default-cost-profile-aws
    version: version-1702705950
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: policy-privileged
      version: version-1705214554
    profile:
      name: default
      version: latest
  type: custom
  version: v2
