apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custombp1234
  project: defaultproject
spec:
  base:
    name: default
    version: 2.3.0
  defaultAddons:
    enableMonitoring: true
  driftWebhook: {}
  type: custom
  version: v1
