apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: defup
  project: defaultproject
spec:
  base:
    name: default-upstream
    version: 2.4.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    enableRookCeph: true
    monitoring:
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v2
