apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: myblueprint
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.5.0
  customAddons:
  - name: cert-manager
    version: v1.13.0
  driftWebhook:
    enabled: true
  type: custom
  version: v1
