apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: networkpolicy1
  project: defaultproject
spec:
  base:
    name: default
    version: 2.5.0
  defaultAddons:
    enableMonitoring: true
  driftWebhook: {}
  networkPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v1
