apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: networkpolicy
  project: defaultproject
spec:
  base:
    name: default
    version: 2.4.0
  costProfile:
    name: default-cost-profile-aws
    version: version-1707548881
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  opaPolicy:
    profile:
      name: test1
      version: v2
  type: custom
  version: v2
