apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: opaonly
  project: defaultproject
spec:
  base:
    name: default
    version: 2.4.0
  customAddons:
  - name: hello-world
    version: "1"
  - name: onpremtest3
    version: v1.0
  - name: onpremtest4
    version: v1.0
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  opaPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: test3
