apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testgoldebbp
  project: defaultproject
spec:
  base:
    name: default
    version: 2.3.0
  customAddons:
  - name: randomaddon
    version: v2
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: golden
  version: v2
