apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test
  project: defaultproject
spec:
  base:
    name: default
    version: 2.4.0
  customAddons:
  - name: v2-infra
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v4
