apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testblueprint12345678
  project: defaultproject
spec:
  base:
    name: default
    version: 2.5.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: 0.0.12
