apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testbp1
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.3.0
  customAddons:
  - name: nginx-latest
    version: v1
  driftWebhook: {}
  type: custom
  version: v2
