apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testdefault
  project: defaultproject
spec:
  base:
    name: default
    version: 2.3.0
  costProfile:
    name: default-cost-profile-aws
    version: version-1707548881
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: testpolicy
      version: v1
    profile:
      name: default
      version: latest
  type: custom
  version: v2
