apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  labels:
    testlabel: $(#environment["fmtest"].testout)$
spec:
  containers:
  - command:
    - sleep
    - "60000"
    image: busybox:latest
    imagePullPolicy: Always
    name: test 
  imagePullSecrets:
  - name: registry-credentials
