apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-nutanix-cluster
  namespace: default
spec:
  encryptedData:
    variables.6: AQDgAcouCUs0KwpRXr5BtEZumtWQO+mK+1vkX1JLaWjcK8OVYYeyNsX621Bt0Are8rpzPA5gncPEy9EA6bWH13tMzO3g7OuJp5DP9VhM3AbiHm1LVx261ZUldruIU1Q8+/VTEcm8bNbm3OYO+yTjBuhkbkg001L2EqW+mY8jDqpWSzhgR/lL9LZFopLSZeH0YXGOVpdugBtS8pBo3wc5VNgUdMxuKUyV4V9Xg7Py3QUBxJ685xHJ6j8MKyAzx7+Fs8r4pm7+rlMW/ID6+hFhtkHImVwLW3JdrD6FAm6xq4DO2bP183m8pkI6+Q05QigiGMdB1PypjYwAE7rvzMTENYuDctCq577ZG8FjdyibkrSAKYeS+BAorAD9NJw6zUUdXuilwxqA
    variables.7: AQBYUFdBJc2uIQp8Jm1KD+kVJ0FpOU3n0ZDe6frKMB+sQk1jmIUq7BZtmcPt3RAn4k5qjTl5M4fkBzhgkWjTUSxiIpsLwX8w7+No8t7IaeX6hg1Bij/Pio4u6rs2sQw1e7FCVbKyG0B6L2ig37M5niBDiZzJJH1rZtf72Sg0gyNWIWMUlzEXtD6vfGZfUtOMHcL1/xfShDpLiR6SZce+qix1FsifOQhyOzYtNGHQQ3hS7jTl+ppQgE9aSSSj36UQWri4TdEC5HkECk2JI6fnhrqvOrMK+N3QkuuvtyBbgDeWwmQJCJyIMLONZaJE8rlRaocniY3WVvzTqv/iOKDLIvP8iizApUmWDRszxixK8hYwgu7uj1O7AnoTbBqt39Wt47TfrvKD
    variables.12: AQDEpKwFpoqmUgyG6o91AqZm0f6dVZnAOWY3v8eoTEuJoQNrnZd7Isa+l29SxY2V6ZXyhiAE6qRP7Ho8keIBqpJI5wovDCHZlRFNQY262YWBLrO3HT6NiAXsDKTm0dIqfR9UYbAkWVQAsagBmX8fATO0IRrIqAnBqXJfCLfY7Xaxndk7YxHSoNNARk1+8tsA/CjDlV8plHTQIyuZGZrZWKcTwQY0D99gpLIpzFSVjvSh3YU99gBAjcdA9TDxthie2qZNhCKuLxHtqW/bVJdp35mYTUViXSe2mvdI6JurfsDTXF2fWcTgn97aWYCaAGO2zlbIwQKGZ5fwNvG0jsxzEuZnQ/oJ2CLCtWQaBB1XhqZ02o1lK5WhXamRzBZ0BJpO6RXx1yinSg==
  template:
    metadata:
      creationTimestamp: null
      name: demo-nutanix-cluster
      namespace: default

