apiVersion: infra.k8smgmt.io/v3
kind: AddonOverride
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: rookceph123
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: cephtest
  resource:
    type: Addon
  type: Helm
  valuesPath:
    name: file://rookceph123/rookceph123.yaml
