apiVersion: infra.k8smgmt.io/v3
kind: AddonOverride
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: test123456
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/clusterType
      value: aws-eks
  resource:
    selector:
      name: vault
    type: Addon
  type: Helm
  valuesPath:
    name: file://test123456/test123456.yaml
