apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: opaoverride1
  project: defaultproject
spec:
  resource:
    selector:
      name: opa-gatekeeper-3.11.0
    type: Workload
  type: Helm
  valuesPath:
    name: file://opaoverride1/opaoverride1.yaml
