apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx1
    testkey: testval1
  annotations:
    rafay.dev/secretstore: csi-aws
    csi-aws.secretstore.rafay.dev/config-1: |
      {
               "secretproviderclass-name": "vijaysspctest",
               "mount-path": "/mnt/secrets-store"
      }
    csi-aws.secretstore.rafay.dev/config-2: |
      {
               "secretproviderclass-name": "vijaysspctest",
               "mount-path": "/mnt/secrets-store-two"
      }
    csi-aws.secretstore.rafay.dev/role-arn: arn:aws:iam::679196758854:role/vijayssecretmanager 
    csi-aws.secretstore.rafay.dev/serviceAccountName: testsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: centos
        command: ["sleep"]
        args:  ["60000"]
