apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drivertest
  namespace: default
spec:
  encryptedData:
    variables.1: AQDLoTAfEsm7n+iHpuSvKxxluquALF8ebag1isFBJiDMp/aJTPmimcCK/sS9yGPlwPVlBl392lIemkgn215tTUSvSh0nbXOlmL225edBumqaxwujJtGc9BJ2CtbCHd/0t6CeAPIlpE1kksMKD7IzHNSCDNUER4xKsRuX1qrdnsij1/zDmcPLJQgudpDODAYDcdmFYAScW+daB0Rpjk9NV/bhOLoeewJbrH92kMjyB6521Fgr+DobRSn+G9kgY92NVziUBFDyXmDoqkKhm8cl0l5Nv9VR8CIQsMiQcC5pSrKyTvWJrr1RoOwLusbQ/eYdTbtg8ZZY0kJ8FLivMRG+0ya48Z8x91wqXKmfbf9QQTcTrw==
  template:
    metadata:
      creationTimestamp: null
      name: drivertest
      namespace: default

