apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: demo-nutanix-cluster
  project: defaultproject
spec:
  secret:
    name: file://artifacts/nutanix-cluster1/sealed-secret.yaml
  template:
    name: nutanix-cluster
    version: v1
    versionState: draft
  variables:
  - name: cluster_uuid
    options:
      override:
        type: allowed
      required: true
    value: 00061e2d-4f4b-0039-0afe-9440c97b55c4
    valueType: text
  - name: masters
    options:
      override:
        type: allowed
      required: true
    value: (["master-0"])
    valueType: hcl
  - name: memory_in_mb
    options:
      override:
        type: allowed
      required: true
    value: "4096"
    valueType: text
  - name: num_sockets
    options:
      override:
        type: allowed
      required: true
    value: "2"
    valueType: text
  - name: nutanix_endpoint
    options:
      override:
        type: allowed
      required: true
    value: 10.38.252.39
    valueType: text
  - name: nutanix_port
    options:
      override:
        type: allowed
      required: true
    value: "9440"
    valueType: text
  - name: password
    options:
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.6
    valueType: text
  - name: ssh_public_key
    options:
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.7
    valueType: text
  - name: subnet_name
    options:
      override:
        type: allowed
      required: true
    value: Primary
    valueType: text
  - name: subnet_uuid
    options:
      override:
        type: allowed
      required: true
    value: 9fc7fe95-e18b-44ee-92bb-c51a06d58044
    valueType: text
  - name: template_name
    options:
      override:
        type: allowed
      required: true
    value: vijaysvm
    valueType: text
  - name: template_uuid
    options:
      override:
        type: allowed
      required: true
    value: 0afc5780-42c9-4e5a-a4df-dbb76c8e55d5
    valueType: text
  - name: username
    options:
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.12
    valueType: text
  - name: vcpus_per_socket
    options:
      override:
        type: allowed
      required: true
    value: "2"
    valueType: text
  - name: vm_prefix
    options:
      override:
        type: allowed
      required: true
    value: demo
    valueType: text
  - name: workers
    options:
      override:
        type: allowed
      required: true
    value: ([])
    valueType: hcl
  - name: cluster_kubernetes_version
    options:
      override:
        type: allowed
    value: v1.29.4
    valueType: text
  - name: cluster_dedicated_masters
    options:
      override:
        type: allowed
    value: false
    valueType: json
  - name: cluster_ha
    options:
      override:
        type: allowed
    value: false
    valueType: json        
