apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijaysmks
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.8
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vijaysmkstest
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.2
      roles:
      - Worker
      - ControlPlane
  proxy: {}
  type: mks
