apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    testkey: testvalue
  name: vijayseks121220242
  project: defaultproject
spec:
  blueprintConfig:
    name: cost-minimal
    version: v1
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      withOIDC: true
    metadata:
      name: vijayseks121220242
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.30"
    network:
      cni:
        name: aws-cni
        params:
          customCniCrdSpec:
            us-west-2a:
            - subnet: subnet-0d2c3359d62594d32
            us-west-2b:
            - subnet: subnet-0e7c514426a237796
            us-west-2c:
            - subnet: subnet-0d03a8d56fee019e4
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 3
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instancesDistribution:
        instanceTypes:
        - t3.xlarge
      maxPodsPerNode: 110
      maxSize: 12
      minSize: 0
      name: ng-3
      privateNetworking: true
      subnets:
      - subnet-0b5454e3766e256cf
      - subnet-0c2ace7c1bd6f389d
      - subnet-01191eb45bbc20289
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.30"
      volumeSize: 80
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      subnets:
        private:
          private-01:
            id: subnet-01191eb45bbc20289
          private-02:
            id: subnet-0c2ace7c1bd6f389d
          private-03:
            id: subnet-0b5454e3766e256cf
  sharing:
    enabled: true
    projects:
    - name: demos
    - {}
    - {}
    - {}
    - name: rafaylab
    - name: system-catalog
  type: aws-eks
