apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helmsample
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAItQJpN+9CdKB6c2+6DN5DHlpmL4zfvR6T87Y+SKLnIFNCujtMSETIGGwAEMhx1miMfu3P9gZ2R8vmCMb2xUnQoSJMnlrAMQj81VjYkyD1qlTU3nZwaTu+uiU6IWVaLYAdjFHYCVnt4S2IeaWgLTkXBYeKTKhWvlw1WU0TXcnex0kZK8WLqZb7tq87ukaC4jJ8Gonz+zI6DBbjZDWwmP/Fgx+Mclus6ggVQSWkr94zINQ1iJ2R64inYL/pKuKVp/DdVDOsIoNYC87zqXdx+/Ov0iflYmKBTy8V4kJZgledpOQvmv7G4V8B5DyyMH1C0U7wcSudTtOrDdE4uH1cfQ0m8x/dnjzHxF+VcmrJCvLCBQWjmD8vjYrqZY45FlVF9/zVhP7G7uOi2lCmhwm7SZp4xpm91fm6qDM=
  template:
    metadata:
      creationTimestamp: null
      name: helmsample
      namespace: default

