apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: fmtestwl
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/fmtestwl/vcluster-0.21.2.tgz
      valuesPaths:
      - name: file://artifacts/fmtestwl/values.yaml
    type: Helm
  namespace: testns
