apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: fmtestwl2
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/fmtestwl2/vcluster-0.21.2.tgz
      valuesPaths:
      - name: file://artifacts/fmtestwl2/values.yaml
    options:
      maxHistory: 10
      timeout: 1m0s
    type: Helm
  namespace: testns
  placement:
    selector: rafay.dev/clusterName=vijayseks121220242
  version: fmtestwl2-v3-202502120023340000
