apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: fmtestwl
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/fmtestwl/vcluster-0.21.2.tgz
      valuesPaths:
      - name: file://artifacts/fmtestwl/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: testns
  placement:
    environment:
      name: drivertest3
    selector: rafay.dev/clusterName=vijayseks121220242
  version: fmtestwl-v2-202502112222190000
