apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: fmtestwl2
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/fmtestwl2/vcluster-0.21.2.tgz
      valuesPaths:
      - name: file://artifacts/fmtestwl2/values.yaml
    type: Helm
  namespace: testns
