apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/testworkload/testworkload.yaml
    type: Yaml
  namespace: defaultns
  placement:
    environment:
      name: drivertest2
    selector: rafay.dev/clusterName=vijayseks121220242
  version: testworkload-v2-202502032027140000
