apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testhelm
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testhelm/vcluster-0.21.2.tgz
      valuesPaths:
      - name: file://artifacts/testhelm/values.yaml
    type: Helm
  namespace: defaultns
