apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload1234
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testworkload1234/secrets-store-csi-driver.tgz
      valuesPaths:
      - name: file://artifacts/testworkload1234/loki-values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: defaultns
  placement:
    selector: rafay.dev/clusterName=mkstestcluster
  version: testworkload1234-v1-202503141758560000
