apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testapp2
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testapp2/tesapp-0.1.0.tgz
      valuesPaths:
      - name: file://artifacts/testapp2/values.yaml
    type: Helm
  namespace: testns
