apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload1234
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testworkload1234/secrets-store-csi-driver.tgz
      valuesPaths:
      - name: file://artifacts/testworkload1234/loki-values.yaml
    type: Helm
  namespace: defaultns
