apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testwlvijays
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testwlvijays/testchart-0.1.0.tgz
      valuesPaths:
      - name: file://artifacts/testwlvijays/values.yaml
    type: Helm
  namespace: defaultns
