apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testapp2
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testapp2/tesapp-0.1.0.tgz
      valuesPaths:
      - name: file://artifacts/testapp2/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: testns
  placement:
    environment:
      name: drivertest3
    selector: rafay.dev/clusterName=vijayseks121220242
  version: testapp2-v4-202502071930500000
