apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: drivertest2
  project: defaultproject
spec:
  secret:
    name: file://artifacts/drivertest2/sealed-secret.yaml
  template:
    name: optouttest
    version: v3
    versionState: draft
  variables:
  - name: password
    options:
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.0
    valueType: text
  - name: username
    options:
      override:
        type: allowed
      required: true
    value: vijays
    valueType: text
