apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: ankit-2
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/ankit-2/ankit-2.yaml
    type: Yaml
  namespace: testns
  placement:
    selector: rafay.dev/clusterName=vijayseks15042024
  version: ankit-2-v12-202407030647420000
