apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: gitworkload
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/gitworkload/hello-0.1.2.tgz
      valuesPaths:
      - name: file://artifacts/gitworkload/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: chaos-mesh
  placement:
    selector: rafay.dev/clusterName=ubuntumkstest
  version: v1
