apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: samplehelmworkload
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/samplehelmworkload/testpackage-0.1.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: testns
  placement:
    selector: rafay.dev/clusterName=vijaysrookceph
  version: samplehelmworkload-v1-202407251958150000
