apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload111
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testworkload111/splunk-otel-collector-0.100.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: demo1
  placement:
    selector: rafay.dev/clusterName=vijaysrookceph
  version: testworkload111-v1-202407231523180000
