apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testwrkld2
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/testwrkld2/testwrkld2.yaml
    type: Yaml
  namespace: ankitns
  placement:
    environment:
      name: fmenv1
    selector: rafay.dev/clusterName=vijaysrookceph
