apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testwkrld
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testwkrld/cluster-agent-1.18.210.tgz
    type: Helm
  namespace: ankitns
