apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload-jef-aea18427
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: charts/hello-world
      repository: helmsample
      revision: main
      valuesPaths:
      - name: charts/hello-world/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: chaos-mesh
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: ubuntumkstest
  version: testworkload-jef-aea18427-v1-202403271831120000
