apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: workload123
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/workload123/testpackage-0.1.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: ankitns
  placement:
    selector: rafay.dev/clusterName=vijaysrookceph
  version: workload123-v3-202407232351390000
