apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijayseks26122023
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          autoScaler: true
          efs: false
          externalDNS: false
          imageBuilder: false
      instanceTypes:
      - t3.xlarge
      labels: {}
      maxSize: 1
      minSize: 0
      name: ngvijayswithdate
      privateNetworking: false
      securityGroups:
        attachIDs: []
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      volumeEncrypted: false
      volumeType: gp3
    metadata:
      name: vijayseks26122023
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.25"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
      subnets:
        private: {}
        public: {}
  type: aws-eks
