apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    testkey: testval
  annotations:
    rafay.dev/secretstore: csi-aws
    csi-aws.secretstore.rafay.dev/config-1: |
      {
               "secretproviderclass-name": "vijaysspctest",
               "mount-path": "/mnt/secrets-store"
      }
    csi-aws.secretstore.rafay.dev/role-arn: arn:aws:iam::679196758854:role/vijayssecretmanager 
    csi-aws.secretstore.rafay.dev/serviceAccountName: testsa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        costcenter: "504216" 
    spec:
      containers:
      - name: nginx
        image: centos
        command: ["sleep"]
        args:  ["60000"]
