apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: eksagent18042024
  project: defaultproject
spec:
  active: true
  cluster:
    name: vijayseks15042024
  sharing:
    enabled: true
    projects:
    - name: production
  type: Cluster
  version: r2.5.0
