apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    costcenter: xyz1234
    env: development
  name: demo-nutanix-cluster
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: 2.7.0
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.30.1
    location: newyorkcity-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: demo-master-0
      operatingSystem: Ubuntu22.04
      privateIP: 10.38.252.60
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 10.38.252.60
        port: "22"
        privateKeyPath: id_ssh
        username: ubuntu
    - arch: amd64
      hostname: demo-master-1
      operatingSystem: Ubuntu22.04
      privateIP: 10.38.252.61
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 10.38.252.61
        port: "22"
        privateKeyPath: id_ssh
        username: ubuntu
    - arch: amd64
      hostname: demo-worker-0
      operatingSystem: Ubuntu22.04
      privateIP: 10.38.252.68
      roles:
      - Worker
      ssh:
        ipAddress: 10.38.252.68
        port: "22"
        privateKeyPath: id_ssh
        username: ubuntu
  type: mks
