apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: secrettestfromtf
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: 2.8.0
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: vpc-cni
      version: latest
    - name: kube-proxy
      version: latest
    - name: coredns
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: true
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceTypes:
      - t3.xlarge
      maxPodsPerNode: 110
      maxSize: 1
      minSize: 1
      name: ng
      privateNetworking: true
      spot: false
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.30"
      volumeEncrypted: true
      volumeIOPS: 3000
      volumeSize: 100
      volumeThroughput: 125
      volumeType: gp3
    metadata:
      name: secrettestfromtf
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.30"
    network:
      cni:
        name: aws-cni
    secretsEncryption:
      encryptExistingSecrets: false
      keyARN: arn:aws:kms:us-west-2:679196758854:key/0e2122a4-3ed5-4a89-a7bf-3dda1b344988
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
  type: aws-eks
