apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijays201820242
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    - name: vpc-cni
      version: latest
    - name: kube-proxy
      version: latest
    - name: coredns
      version: latest
    iam:
      serviceAccounts: []
      withOIDC: true
    metadata:
      name: vijays201820242
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.29"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      instanceType: t3.xlarge
      maxPodsPerNode: 50
      maxSize: 4
      minSize: 0
      name: ng-1
      privateNetworking: true
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.29"
      volumeEncrypted: false
      volumeSize: 80
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
  type: aws-eks
