apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: crashtest
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/crashtest/crashtest.yaml
    type: Yaml
  namespace: cert-manager
  placement:
    selector: rafay.dev/clusterName=eks-cluster-vijays-09032023
  version: crashtest-v2
