apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: fsnew1
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/fsnew/fs-0.1.0.tgz
      valuesPaths:
      - name: file://artifacts/fsnew/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: jobtest
  placement:
    selector: rafay.dev/clusterName=testcluster1
