apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: rafaysyssynctest3
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: deploy2.yaml
      repository: rafaysyssync
      revision: master
    type: Yaml
  namespace: cert-manager
  placement:
    selector: rafay.dev/clusterName=eks-cluster-vijays-09032023
  version: rafaysyssynctest2-v1
