apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload-e46a7373
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: deploy-green.yaml
      repository: myrepo
      revision: master
    options: {}
    type: Yaml
  namespace: demo3
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: mkstestcluster
  version: testworkload-e46a7373-v11-202306271807200000
