apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testwrokload1-7652ece1
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: green/
      repository: myrepo
      revision: master
      valuesPaths:
      - name: green/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: demo3
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: mkstestcluster
  version: testwrokload1-7652ece1-v2-202306280831330000
