apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: wltestvijay
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-bitnami
      chartName: nginx
      chartVersion: 13.2.33
      valuesPaths:
      - name: file://nginx11/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: cert-manager
  placement:
    selector: rafay.dev/clusterName=eks-cluster-vijays-09032023
  version: wltestvijay-v1
