apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    Owner: vijay
  name: vijayseks15042024
  project: defaultproject
spec:
  blueprintConfig:
    name: custombp
    version: v3
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      serviceAccountRoleARN: arn:aws:iam::679196758854:role/ebscsicontrollervijaysrole20
      version: latest
    - name: vpc-cni
      serviceAccountRoleARN: arn:aws:iam::679196758854:role/vijaysvpccnirole20
      version: v1.18.1-eksbuild.1
    iam:
      serviceAccounts:
      - attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
        metadata:
          name: ebs-csi-controller-sa
          namespace: kube-system
        roleName: ebscsicontrollervijaysrole20
        roleOnly: true
      - attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        metadata:
          name: aws-node
          namespace: kube-system
        roleName: vijaysvpccnirole20
        roleOnly: true
      withOIDC: true
    metadata:
      name: vijayseks15042024
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.29"
    network:
      cni:
        name: aws-cni
        params:
          customCniCrdSpec:
            us-west-2a:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-04a4f0d7703a6019d
            us-west-2b:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-0ce592c166364df2b
            us-west-2c:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-06837762030effed4
    nodeGroups:
    - amiFamily: Ubuntu2004
      desiredCapacity: 2
      iam:
        instanceRoleARN: arn:aws:iam::679196758854:role/vijaysworkerrole
      instanceType: t3.xlarge
      maxSize: 6
      minSize: 0
      name: vijays-ng
      privateNetworking: true
      ssh:
        allow: true
        publicKeyName: awskey
      subnets:
      - subnet-01191eb45bbc20289
      - subnet-0c2ace7c1bd6f389d
      - subnet-0700983bf90ca0ec6
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.28"
      volumeEncrypted: true
      volumeSize: 80
      volumeType: gp3
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      id: null
      subnets:
        private:
          private-01:
            id: subnet-01191eb45bbc20289
          private-02:
            id: subnet-0c2ace7c1bd6f389d
          private-03:
            id: subnet-0700983bf90ca0ec6
  sharing:
    enabled: true
    projects:
    - name: production
  type: aws-eks
