apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijayseks2405202410
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: vijaysrole
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    - name: vpc-cni
      version: v1.18.1-eksbuild.1
    iam:
      withOIDC: true
    metadata:
      name: vijayseks2405202410
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.29"
    network:
      cni:
        name: aws-cni
        params:
          customCniCrdSpec:
            us-west-2a:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-04a4f0d7703a6019d
            us-west-2b:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-0ce592c166364df2b
            us-west-2c:
            - securityGroups:
              - sg-0f4021b2dc09124d4
              subnet: subnet-06837762030effed4
    nodeGroups:
    - ami: ami-09e9b983e04338781
      desiredCapacity: 1
      iam:
        instanceRoleARN: arn:aws:iam::679196758854:role/vijaysworkerrole
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: vijays-ng
      preBootstrapCommands:
      - |
        #!/bin/bash
        echo Z3JlcCAtQSA1MDAgLW0xICJeL2V0Yy9la3MvYm9vdHN0cmFwLnNoIiAvdmFyL2xpYi9jbG91ZC9pbnN0YW5jZXMvJChlYzItbWV0YWRhdGEgLWkgLS1xdWlldCkvc2NyaXB0cy9ydW5jbWQgfCBzZWQgJ3MvXlwvdmFyXC9saWJcL2Nsb3VkXC9pbnN0YW5jZXNcL2ktLipcL3NjcmlwdHNcL3J1bmNtZC0vL2cnIHwgZ3JlcCAtbSAxIC1CIDUwMCAiL3Zhci9zcG9vbC9jcm9uL3Jvb3QiIHwgaGVhZCAtbiAtMSB8IHNlZCAicy8nXFxcJy8vZyIgfCB0YWlsIC1uICsyIHwgc2VkICdzL1wvdXNyXC9iaW5cL2F3cy1pYW0tYXV0aGVudGljYXRvci9cL3VzclwvbG9jYWxcL2JpblwvYXdzLWlhbS1hdXRoZW50aWNhdG9yLycgfCBiYXNoIApncmVwIC1vICIvdXNyL2xvY2FsL2Jpbi9yY3J5cHQuKjsiIC92YXIvbGliL2Nsb3VkL2luc3RhbmNlcy8kKGVjMi1tZXRhZGF0YSAtaSAtLXF1aWV0KS9zY3JpcHRzL3J1bmNtZCB8IGhlYWQgLW4gMSB8IHRyIC1kICInIiB8IHRyIC1kICI7IiB8IGJhc2gKZ3JlcCAtbyAiL3Vzci9sb2NhbC9iaW4vcmNyeXB0Lio7IiAvdmFyL2xpYi9jbG91ZC9pbnN0YW5jZXMvJChlYzItbWV0YWRhdGEgLWkgLS1xdWlldCkvc2NyaXB0cy9ydW5jbWQgPiAvZGV2L251bGwKaWYgWyAkPyAtbmUgMCBdCnRoZW4KZWNobyBMUzB0Q21Gd2FWWmxjbk5wYjI0NklHNXZaR1V1Wld0ekxtRjNjeTkyTVdGc2NHaGhNUXByYVc1a09pQk9iMlJsUTI5dVptbG5Dbk53WldNNkNpQWdZMngxYzNSbGNqb0tJQ0FnSUc1aGJXVTZJQ1I3UTB4VlUxUkZVbDlPUVUxRmZRb2dJQ0FnWVhCcFUyVnlkbVZ5Ulc1a2NHOXBiblE2SUNSN1JVNUVVRTlKVGxSOUNpQWdJQ0JqWlhKMGFXWnBZMkYwWlVGMWRHaHZjbWwwZVRvZ0pIdERSVkpVUkVGVVFYMEtJQ0FnSUdOcFpISTZJQ1I3UTBsRVVuMEsgfCBiYXNlNjQgLWQgPiAvdG1wL25vZGV0ZW1wbGF0ZV9jb25maWcKcmVhZCAtciBDTFVTVEVSX05BTUUgRU5EUE9JTlQgQ0VSVERBVEEgQ0lEUiA8PDwgYGF3cyBla3MgZGVzY3JpYmUtY2x1c3RlciAtLW5hbWUgJDEgfCBqcSAnLmNsdXN0ZXIgfCBbLm5hbWUsLmVuZHBvaW50LC5jZXJ0aWZpY2F0ZUF1dGhvcml0eS5kYXRhLC5rdWJlcm5ldGVzTmV0d29ya0NvbmZpZy5zZXJ2aWNlSXB2NENpZHJdIHwgQHRzdicgLXJgCmV4cG9ydCBDTFVTVEVSX05BTUUgRU5EUE9JTlQgQ0VSVERBVEEgQ0lEUgplbnZzdWJzdCA8IC90bXAvbm9kZXRlbXBsYXRlX2NvbmZpZyA+IC9yb290L25vZGVjb25maWcKbm9kZWFkbSBpbml0IC1jIGZpbGU6Ly8vcm9vdC9ub2RlY29uZmlnCmZpCg== | base64 -d > /root/file
        chmod u+x /root/file
        echo W1VuaXRdCkRlc2NyaXB0aW9uPU15IEpvYgoKW1NlcnZpY2VdClR5cGU9c2ltcGxlClJlc3RhcnQ9YWx3YXlzCkV4ZWNTdGFydD0vYmluL2Jhc2ggL3Jvb3QvZmlsZQo= | base64 -d | sed 's/\/root\/file/\/root\/file vijayseks2405202410/' > /etc/systemd/system/myjob.service
        echo W1VuaXRdCkRlc2NyaXB0aW9uPU15IFRpbWVyCgpbVGltZXJdCk9uQ2FsZW5kYXI9Ki0qLSogKjowLzUKUGVyc2lzdGVudD10cnVlClVuaXQ9bXlqb2Iuc2VydmljZQoKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0Cg== | base64 -d > /etc/systemd/system/myjob.timer
        systemctl daemon-reload
        systemctl enable myjob.timer --now
      privateNetworking: true
      ssh:
        allow: true
        publicKeyName: awskey
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.29"
      volumeEncrypted: true
      volumeSize: 80
      volumeType: gp3
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      id: null
      subnets:
        private:
          private-01:
            id: subnet-01191eb45bbc20289
          private-02:
            id: subnet-0c2ace7c1bd6f389d
          private-03:
            id: subnet-0700983bf90ca0ec6
  type: aws-eks
